 "age": 35,
    "gender" : "female",
    "weight" : 70,
    "height" : 172,
    "temperature" :38.2,
    "blood_pressure" :150,
    "sleep" : 7,
    "heart_rate" :116,
    "smoking" : "no",
    "alcohol" : "yes"